version: '3'
services:
    nextjs:
        build:
            context: ./nextjs
            dockerfile: ./Dockerfile
        volumes:
            - ./nextjs/src:/app
            - nextjs_node_modules:/app/node_modules
        ports:
            - '3000:3000'
        depends_on:
            - laravel
        tty: true

    laravel:
        build:
            context: ./laravel
            dockerfile: ./Dockerfile
        volumes:
            - ./laravel/src:/app
        ports:
            - '8000:8000'
        depends_on:
            - postgres
            - redis
        tty: true

    postgres:
        image: postgres:15
        ports:
            - '5432:5432'
        volumes:
            - db_store:/var/lib/postgresql/data
            # 公式postgresイメージの仕様
            # 初回起動時に、/docker-entrypoint-initdb.d内のsqlを実行する
            - ./postgres/scripts:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        tty: true
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - redis_store:/data
        tty: true
volumes:
    nextjs_node_modules:
    db_store:
    redis_store:
